# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            三生如梦
tagline:          'A Jekyll theme'
description:      'Gao Yan的技术博客 <a href="https://github.com/gaoyan10" target="_blank">Gao Yan</a> .'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Gao Yan'
  url:            http://blog.csdn.net/gaoyan10

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gaoyan10
